# Generated by Django 5.0.6 on 2024-08-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/entries/'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/entries/'),
        ),
    ]
