# Generated by Django 5.0.6 on 2024-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedicament',
            name='icon',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmedicament',
            name='type',
            field=models.CharField(choices=[('tablet', 'Comprimé'), ('syrup', 'Sirop'), ('capsule', 'Capsule'), ('ointment', 'Pommade'), ('injection', 'Injection'), ('drop', 'Goutte'), ('cream', 'Crème'), ('suppository', 'Suppositoire')], default='tablet', max_length=20),
        ),
        migrations.AddField(
            model_name='medicament',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='medicaments/icons/'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='type',
            field=models.CharField(choices=[('tablet', 'Comprimé'), ('syrup', 'Sirop'), ('capsule', 'Capsule'), ('ointment', 'Pommade'), ('injection', 'Injection'), ('drop', 'Goutte'), ('cream', 'Crème'), ('suppository', 'Suppositoire')], default='tablet', max_length=20),
        ),
    ]
